matrix:
    include:
      - language: python
        python:
          -"3.6"
        install:
          - pip install -r requirements.txt

        before_script:

          - "export DISPLAY=:99.0"

          - "sh -e /etc/init.d/xvfb start"

          - sleep 3 # give xvfb some time to start

        script:
         - pytest -v
       
     - language: node_js
       node_js: "8"
       script:
         - npm test
         - npm run build

